// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package rest is a generated GoMock package.
package rest

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	model "github.com/s21platform/materials-service/internal/model"
)

// MockDBRepo is a mock of DBRepo interface.
type MockDBRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDBRepoMockRecorder
}

// MockDBRepoMockRecorder is the mock recorder for MockDBRepo.
type MockDBRepoMockRecorder struct {
	mock *MockDBRepo
}

// NewMockDBRepo creates a new mock instance.
func NewMockDBRepo(ctrl *gomock.Controller) *MockDBRepo {
	mock := &MockDBRepo{ctrl: ctrl}
	mock.recorder = &MockDBRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBRepo) EXPECT() *MockDBRepoMockRecorder {
	return m.recorder
}

// AddLike mocks base method.
func (m *MockDBRepo) AddLike(ctx context.Context, materialUUID, userUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLike", ctx, materialUUID, userUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLike indicates an expected call of AddLike.
func (mr *MockDBRepoMockRecorder) AddLike(ctx, materialUUID, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLike", reflect.TypeOf((*MockDBRepo)(nil).AddLike), ctx, materialUUID, userUUID)
}

// CheckLike mocks base method.
func (m *MockDBRepo) CheckLike(ctx context.Context, materialUUID, userUUID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLike", ctx, materialUUID, userUUID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLike indicates an expected call of CheckLike.
func (mr *MockDBRepoMockRecorder) CheckLike(ctx, materialUUID, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLike", reflect.TypeOf((*MockDBRepo)(nil).CheckLike), ctx, materialUUID, userUUID)
}

// EditMaterial mocks base method.
func (m *MockDBRepo) EditMaterial(ctx context.Context, material *model.EditMaterial) (*model.Material, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMaterial", ctx, material)
	ret0, _ := ret[0].(*model.Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditMaterial indicates an expected call of EditMaterial.
func (mr *MockDBRepoMockRecorder) EditMaterial(ctx, material interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMaterial", reflect.TypeOf((*MockDBRepo)(nil).EditMaterial), ctx, material)
}

// GetAllMaterials mocks base method.
func (m *MockDBRepo) GetAllMaterials(ctx context.Context, offset, limit int) (*model.MaterialList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMaterials", ctx, offset, limit)
	ret0, _ := ret[0].(*model.MaterialList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMaterials indicates an expected call of GetAllMaterials.
func (mr *MockDBRepoMockRecorder) GetAllMaterials(ctx, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMaterials", reflect.TypeOf((*MockDBRepo)(nil).GetAllMaterials), ctx, offset, limit)
}

// GetLikesCount mocks base method.
func (m *MockDBRepo) GetLikesCount(ctx context.Context, materialUUID string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikesCount", ctx, materialUUID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikesCount indicates an expected call of GetLikesCount.
func (mr *MockDBRepoMockRecorder) GetLikesCount(ctx, materialUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikesCount", reflect.TypeOf((*MockDBRepo)(nil).GetLikesCount), ctx, materialUUID)
}

// GetMaterial mocks base method.
func (m *MockDBRepo) GetMaterial(ctx context.Context, materialUUID string) (*model.Material, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterial", ctx, materialUUID)
	ret0, _ := ret[0].(*model.Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaterial indicates an expected call of GetMaterial.
func (mr *MockDBRepoMockRecorder) GetMaterial(ctx, materialUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterial", reflect.TypeOf((*MockDBRepo)(nil).GetMaterial), ctx, materialUUID)
}

// GetMaterialOwnerUUID mocks base method.
func (m *MockDBRepo) GetMaterialOwnerUUID(ctx context.Context, materialUUID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterialOwnerUUID", ctx, materialUUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaterialOwnerUUID indicates an expected call of GetMaterialOwnerUUID.
func (mr *MockDBRepoMockRecorder) GetMaterialOwnerUUID(ctx, materialUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterialOwnerUUID", reflect.TypeOf((*MockDBRepo)(nil).GetMaterialOwnerUUID), ctx, materialUUID)
}

// MaterialExists mocks base method.
func (m *MockDBRepo) MaterialExists(ctx context.Context, materialUUID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaterialExists", ctx, materialUUID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MaterialExists indicates an expected call of MaterialExists.
func (mr *MockDBRepoMockRecorder) MaterialExists(ctx, materialUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaterialExists", reflect.TypeOf((*MockDBRepo)(nil).MaterialExists), ctx, materialUUID)
}

// PublishMaterial mocks base method.
func (m *MockDBRepo) PublishMaterial(ctx context.Context, materialUUID string) (*model.Material, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMaterial", ctx, materialUUID)
	ret0, _ := ret[0].(*model.Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishMaterial indicates an expected call of PublishMaterial.
func (mr *MockDBRepoMockRecorder) PublishMaterial(ctx, materialUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMaterial", reflect.TypeOf((*MockDBRepo)(nil).PublishMaterial), ctx, materialUUID)
}

// RemoveLike mocks base method.
func (m *MockDBRepo) RemoveLike(ctx context.Context, materialUUID, userUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLike", ctx, materialUUID, userUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLike indicates an expected call of RemoveLike.
func (mr *MockDBRepoMockRecorder) RemoveLike(ctx, materialUUID, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLike", reflect.TypeOf((*MockDBRepo)(nil).RemoveLike), ctx, materialUUID, userUUID)
}

// SaveDraftMaterial mocks base method.
func (m *MockDBRepo) SaveDraftMaterial(ctx context.Context, ownerUUID string, material *model.SaveDraftMaterial) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDraftMaterial", ctx, ownerUUID, material)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveDraftMaterial indicates an expected call of SaveDraftMaterial.
func (mr *MockDBRepoMockRecorder) SaveDraftMaterial(ctx, ownerUUID, material interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDraftMaterial", reflect.TypeOf((*MockDBRepo)(nil).SaveDraftMaterial), ctx, ownerUUID, material)
}

// UpdateLikesCount mocks base method.
func (m *MockDBRepo) UpdateLikesCount(ctx context.Context, materialUUID string, likesCount int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLikesCount", ctx, materialUUID, likesCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLikesCount indicates an expected call of UpdateLikesCount.
func (mr *MockDBRepoMockRecorder) UpdateLikesCount(ctx, materialUUID, likesCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLikesCount", reflect.TypeOf((*MockDBRepo)(nil).UpdateLikesCount), ctx, materialUUID, likesCount)
}

// WithTx mocks base method.
func (m *MockDBRepo) WithTx(ctx context.Context, cb func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, cb)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockDBRepoMockRecorder) WithTx(ctx, cb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockDBRepo)(nil).WithTx), ctx, cb)
}

// MockKafkaProducer is a mock of KafkaProducer interface.
type MockKafkaProducer struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaProducerMockRecorder
}

// MockKafkaProducerMockRecorder is the mock recorder for MockKafkaProducer.
type MockKafkaProducerMockRecorder struct {
	mock *MockKafkaProducer
}

// NewMockKafkaProducer creates a new mock instance.
func NewMockKafkaProducer(ctrl *gomock.Controller) *MockKafkaProducer {
	mock := &MockKafkaProducer{ctrl: ctrl}
	mock.recorder = &MockKafkaProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaProducer) EXPECT() *MockKafkaProducerMockRecorder {
	return m.recorder
}

// ProduceMessage mocks base method.
func (m *MockKafkaProducer) ProduceMessage(ctx context.Context, message, key interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProduceMessage", ctx, message, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProduceMessage indicates an expected call of ProduceMessage.
func (mr *MockKafkaProducerMockRecorder) ProduceMessage(ctx, message, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceMessage", reflect.TypeOf((*MockKafkaProducer)(nil).ProduceMessage), ctx, message, key)
}

// MockRedisRepo is a mock of RedisRepo interface.
type MockRedisRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRedisRepoMockRecorder
}

// MockRedisRepoMockRecorder is the mock recorder for MockRedisRepo.
type MockRedisRepoMockRecorder struct {
	mock *MockRedisRepo
}

// NewMockRedisRepo creates a new mock instance.
func NewMockRedisRepo(ctrl *gomock.Controller) *MockRedisRepo {
	mock := &MockRedisRepo{ctrl: ctrl}
	mock.recorder = &MockRedisRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisRepo) EXPECT() *MockRedisRepoMockRecorder {
	return m.recorder
}

// GetMaterial mocks base method.
func (m *MockRedisRepo) GetMaterial(ctx context.Context, uuid string) (*model.Material, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterial", ctx, uuid)
	ret0, _ := ret[0].(*model.Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaterial indicates an expected call of GetMaterial.
func (mr *MockRedisRepoMockRecorder) GetMaterial(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterial", reflect.TypeOf((*MockRedisRepo)(nil).GetMaterial), ctx, uuid)
}

// SetMaterial mocks base method.
func (m *MockRedisRepo) SetMaterial(ctx context.Context, material *model.Material, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMaterial", ctx, material, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMaterial indicates an expected call of SetMaterial.
func (mr *MockRedisRepoMockRecorder) SetMaterial(ctx, material, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaterial", reflect.TypeOf((*MockRedisRepo)(nil).SetMaterial), ctx, material, ttl)
}
