// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/s21platform/materials-service/internal/model"
)

// MockDBRepo is a mock of DBRepo interface.
type MockDBRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDBRepoMockRecorder
}

// MockDBRepoMockRecorder is the mock recorder for MockDBRepo.
type MockDBRepoMockRecorder struct {
	mock *MockDBRepo
}

// NewMockDBRepo creates a new mock instance.
func NewMockDBRepo(ctrl *gomock.Controller) *MockDBRepo {
	mock := &MockDBRepo{ctrl: ctrl}
	mock.recorder = &MockDBRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBRepo) EXPECT() *MockDBRepoMockRecorder {
	return m.recorder
}

// EditMaterial mocks base method.
func (m *MockDBRepo) EditMaterial(ctx context.Context, material *model.EditMaterial) (*model.Material, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMaterial", ctx, material)
	ret0, _ := ret[0].(*model.Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditMaterial indicates an expected call of EditMaterial.
func (mr *MockDBRepoMockRecorder) EditMaterial(ctx, material interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMaterial", reflect.TypeOf((*MockDBRepo)(nil).EditMaterial), ctx, material)
}

// GetAllMaterials mocks base method.
func (m *MockDBRepo) GetAllMaterials(ctx context.Context) (*model.MaterialList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMaterials", ctx)
	ret0, _ := ret[0].(*model.MaterialList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMaterials indicates an expected call of GetAllMaterials.
func (mr *MockDBRepoMockRecorder) GetAllMaterials(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMaterials", reflect.TypeOf((*MockDBRepo)(nil).GetAllMaterials), ctx)
}

// GetMaterial mocks base method.
func (m *MockDBRepo) GetMaterial(ctx context.Context, uuid string) (*model.Material, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterial", ctx, uuid)
	ret0, _ := ret[0].(*model.Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaterial indicates an expected call of GetMaterial.
func (mr *MockDBRepoMockRecorder) GetMaterial(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterial", reflect.TypeOf((*MockDBRepo)(nil).GetMaterial), ctx, uuid)
}

// GetMaterialOwnerUUID mocks base method.
func (m *MockDBRepo) GetMaterialOwnerUUID(ctx context.Context, uuid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterialOwnerUUID", ctx, uuid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaterialOwnerUUID indicates an expected call of GetMaterialOwnerUUID.
func (mr *MockDBRepoMockRecorder) GetMaterialOwnerUUID(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterialOwnerUUID", reflect.TypeOf((*MockDBRepo)(nil).GetMaterialOwnerUUID), ctx, uuid)
}

// PublishMaterial mocks base method.
func (m *MockDBRepo) PublishMaterial(ctx context.Context, material *model.Material) (*model.Material, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMaterial", ctx, material)
	ret0, _ := ret[0].(*model.Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishMaterial indicates an expected call of PublishMaterial.
func (mr *MockDBRepoMockRecorder) PublishMaterial(ctx, material interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMaterial", reflect.TypeOf((*MockDBRepo)(nil).PublishMaterial), ctx, material)
}

// SaveDraftMaterial mocks base method.
func (m *MockDBRepo) SaveDraftMaterial(ctx context.Context, ownerUUID string, material *model.SaveDraftMaterial) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDraftMaterial", ctx, ownerUUID, material)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveDraftMaterial indicates an expected call of SaveDraftMaterial.
func (mr *MockDBRepoMockRecorder) SaveDraftMaterial(ctx, ownerUUID, material interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDraftMaterial", reflect.TypeOf((*MockDBRepo)(nil).SaveDraftMaterial), ctx, ownerUUID, material)
}
