// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/materials.proto

package materials

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMaterialIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // UUID материала
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaterialIn) Reset() {
	*x = GetMaterialIn{}
	mi := &file_api_materials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaterialIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaterialIn) ProtoMessage() {}

func (x *GetMaterialIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaterialIn.ProtoReflect.Descriptor instead.
func (*GetMaterialIn) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{0}
}

func (x *GetMaterialIn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetMaterialOut struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uuid            string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	OwnerUuid       string                 `protobuf:"bytes,2,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`                      // UUID владельца материала
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                               // Заголовок материала
	CoverImageUrl   string                 `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`        // URL обложки материала
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                                   // Описание материала
	Content         string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                                           // Содержимое материала
	ReadTimeMinutes int32                  `protobuf:"varint,7,opt,name=read_time_minutes,json=readTimeMinutes,proto3" json:"read_time_minutes,omitempty"` // Время чтения в минутах
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMaterialOut) Reset() {
	*x = GetMaterialOut{}
	mi := &file_api_materials_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaterialOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaterialOut) ProtoMessage() {}

func (x *GetMaterialOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaterialOut.ProtoReflect.Descriptor instead.
func (*GetMaterialOut) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{1}
}

func (x *GetMaterialOut) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetMaterialOut) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *GetMaterialOut) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetMaterialOut) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *GetMaterialOut) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetMaterialOut) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetMaterialOut) GetReadTimeMinutes() int32 {
	if x != nil {
		return x.ReadTimeMinutes
	}
	return 0
}

var File_api_materials_proto protoreflect.FileDescriptor

const file_api_materials_proto_rawDesc = "" +
	"\n" +
	"\x13api/materials.proto\"#\n" +
	"\rGetMaterialIn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xe9\x01\n" +
	"\x0eGetMaterialOut\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x02 \x01(\tR\townerUuid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12&\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tR\rcoverImageUrl\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12*\n" +
	"\x11read_time_minutes\x18\a \x01(\x05R\x0freadTimeMinutes2D\n" +
	"\x10MaterialsService\x120\n" +
	"\vGetMaterial\x12\x0e.GetMaterialIn\x1a\x0f.GetMaterialOut\"\x00B\x0fZ\rpkg/materialsb\x06proto3"

var (
	file_api_materials_proto_rawDescOnce sync.Once
	file_api_materials_proto_rawDescData []byte
)

func file_api_materials_proto_rawDescGZIP() []byte {
	file_api_materials_proto_rawDescOnce.Do(func() {
		file_api_materials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_materials_proto_rawDesc), len(file_api_materials_proto_rawDesc)))
	})
	return file_api_materials_proto_rawDescData
}

var file_api_materials_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_materials_proto_goTypes = []any{
	(*GetMaterialIn)(nil),  // 0: GetMaterialIn
	(*GetMaterialOut)(nil), // 1: GetMaterialOut
}
var file_api_materials_proto_depIdxs = []int32{
	0, // 0: MaterialsService.GetMaterial:input_type -> GetMaterialIn
	1, // 1: MaterialsService.GetMaterial:output_type -> GetMaterialOut
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_materials_proto_init() }
func file_api_materials_proto_init() {
	if File_api_materials_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_materials_proto_rawDesc), len(file_api_materials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_materials_proto_goTypes,
		DependencyIndexes: file_api_materials_proto_depIdxs,
		MessageInfos:      file_api_materials_proto_msgTypes,
	}.Build()
	File_api_materials_proto = out.File
	file_api_materials_proto_goTypes = nil
	file_api_materials_proto_depIdxs = nil
}
