// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/materials.proto

package materials

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveDraftMaterialIn struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                               // Заголовок материала
	CoverImageUrl   string                 `protobuf:"bytes,2,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`        // URL обложки материала
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                   // Описание материала
	Content         string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                                           // Содержимое материала
	ReadTimeMinutes int32                  `protobuf:"varint,5,opt,name=read_time_minutes,json=readTimeMinutes,proto3" json:"read_time_minutes,omitempty"` // Время чтения в минутах
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SaveDraftMaterialIn) Reset() {
	*x = SaveDraftMaterialIn{}
	mi := &file_api_materials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDraftMaterialIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDraftMaterialIn) ProtoMessage() {}

func (x *SaveDraftMaterialIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDraftMaterialIn.ProtoReflect.Descriptor instead.
func (*SaveDraftMaterialIn) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{0}
}

func (x *SaveDraftMaterialIn) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SaveDraftMaterialIn) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *SaveDraftMaterialIn) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SaveDraftMaterialIn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SaveDraftMaterialIn) GetReadTimeMinutes() int32 {
	if x != nil {
		return x.ReadTimeMinutes
	}
	return 0
}

type SaveDraftMaterialOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // UUID созданного материала
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDraftMaterialOut) Reset() {
	*x = SaveDraftMaterialOut{}
	mi := &file_api_materials_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDraftMaterialOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDraftMaterialOut) ProtoMessage() {}

func (x *SaveDraftMaterialOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDraftMaterialOut.ProtoReflect.Descriptor instead.
func (*SaveDraftMaterialOut) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{1}
}

func (x *SaveDraftMaterialOut) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetMaterialIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // UUID материала
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaterialIn) Reset() {
	*x = GetMaterialIn{}
	mi := &file_api_materials_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaterialIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaterialIn) ProtoMessage() {}

func (x *GetMaterialIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaterialIn.ProtoReflect.Descriptor instead.
func (*GetMaterialIn) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{2}
}

func (x *GetMaterialIn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetMaterialOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"` // Весь материал
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaterialOut) Reset() {
	*x = GetMaterialOut{}
	mi := &file_api_materials_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaterialOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaterialOut) ProtoMessage() {}

func (x *GetMaterialOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaterialOut.ProtoReflect.Descriptor instead.
func (*GetMaterialOut) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{3}
}

func (x *GetMaterialOut) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

type Material struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uuid            string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	OwnerUuid       string                 `protobuf:"bytes,2,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`                      // UUID владельца материала
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                               // Заголовок материала
	CoverImageUrl   string                 `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`        // URL обложки материала
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                                   // Описание материала
	Content         string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                                           // Содержимое материала
	ReadTimeMinutes int32                  `protobuf:"varint,7,opt,name=read_time_minutes,json=readTimeMinutes,proto3" json:"read_time_minutes,omitempty"` // Время чтения в минутах
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`                                             // Статус материала
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                      // Время создания
	EditedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`                        // Время последнего редактирования
	PublishedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`               // Время публикации
	ArchivedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`                  // Время архивации
	DeletedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`                     // Время удаления
	LikesCount      int32                  `protobuf:"varint,14,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`                 // Количество лайков
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Material) Reset() {
	*x = Material{}
	mi := &file_api_materials_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Material) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Material) ProtoMessage() {}

func (x *Material) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Material.ProtoReflect.Descriptor instead.
func (*Material) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{4}
}

func (x *Material) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Material) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *Material) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Material) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *Material) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Material) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Material) GetReadTimeMinutes() int32 {
	if x != nil {
		return x.ReadTimeMinutes
	}
	return 0
}

func (x *Material) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Material) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Material) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

func (x *Material) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Material) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

func (x *Material) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Material) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

type GetAllMaterialsOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialList  []*Material            `protobuf:"bytes,1,rep,name=material_list,json=materialList,proto3" json:"material_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMaterialsOut) Reset() {
	*x = GetAllMaterialsOut{}
	mi := &file_api_materials_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMaterialsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMaterialsOut) ProtoMessage() {}

func (x *GetAllMaterialsOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMaterialsOut.ProtoReflect.Descriptor instead.
func (*GetAllMaterialsOut) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllMaterialsOut) GetMaterialList() []*Material {
	if x != nil {
		return x.MaterialList
	}
	return nil
}

type EditMaterialIn struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uuid            string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                                                 // UUID материала
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                               // Заголовок материала
	CoverImageUrl   string                 `protobuf:"bytes,3,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`        // URL обложки материала
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                                   // Описание материала
	Content         string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                                           // Содержание материала
	ReadTimeMinutes int32                  `protobuf:"varint,6,opt,name=read_time_minutes,json=readTimeMinutes,proto3" json:"read_time_minutes,omitempty"` // Время чтения в минутах
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EditMaterialIn) Reset() {
	*x = EditMaterialIn{}
	mi := &file_api_materials_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMaterialIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMaterialIn) ProtoMessage() {}

func (x *EditMaterialIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMaterialIn.ProtoReflect.Descriptor instead.
func (*EditMaterialIn) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{6}
}

func (x *EditMaterialIn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *EditMaterialIn) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditMaterialIn) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *EditMaterialIn) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EditMaterialIn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EditMaterialIn) GetReadTimeMinutes() int32 {
	if x != nil {
		return x.ReadTimeMinutes
	}
	return 0
}

type EditMaterialOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"` // Весь материал
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMaterialOut) Reset() {
	*x = EditMaterialOut{}
	mi := &file_api_materials_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMaterialOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMaterialOut) ProtoMessage() {}

func (x *EditMaterialOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMaterialOut.ProtoReflect.Descriptor instead.
func (*EditMaterialOut) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{7}
}

func (x *EditMaterialOut) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

type DeleteMaterialIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMaterialIn) Reset() {
	*x = DeleteMaterialIn{}
	mi := &file_api_materials_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMaterialIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMaterialIn) ProtoMessage() {}

func (x *DeleteMaterialIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMaterialIn.ProtoReflect.Descriptor instead.
func (*DeleteMaterialIn) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMaterialIn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type PublishMaterialIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // UUID материала
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMaterialIn) Reset() {
	*x = PublishMaterialIn{}
	mi := &file_api_materials_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMaterialIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMaterialIn) ProtoMessage() {}

func (x *PublishMaterialIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMaterialIn.ProtoReflect.Descriptor instead.
func (*PublishMaterialIn) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{9}
}

func (x *PublishMaterialIn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type PublishMaterialOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"` // Весь материал
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMaterialOut) Reset() {
	*x = PublishMaterialOut{}
	mi := &file_api_materials_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMaterialOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMaterialOut) ProtoMessage() {}

func (x *PublishMaterialOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMaterialOut.ProtoReflect.Descriptor instead.
func (*PublishMaterialOut) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{10}
}

func (x *PublishMaterialOut) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

type ArchivedMaterialIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchivedMaterialIn) Reset() {
	*x = ArchivedMaterialIn{}
	mi := &file_api_materials_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchivedMaterialIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivedMaterialIn) ProtoMessage() {}

func (x *ArchivedMaterialIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivedMaterialIn.ProtoReflect.Descriptor instead.
func (*ArchivedMaterialIn) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{11}
}

func (x *ArchivedMaterialIn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ToggleLikeIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialUuid  string                 `protobuf:"bytes,1,opt,name=material_uuid,json=materialUuid,proto3" json:"material_uuid,omitempty"` // UUID материала
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeIn) Reset() {
	*x = ToggleLikeIn{}
	mi := &file_api_materials_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeIn) ProtoMessage() {}

func (x *ToggleLikeIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeIn.ProtoReflect.Descriptor instead.
func (*ToggleLikeIn) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{12}
}

func (x *ToggleLikeIn) GetMaterialUuid() string {
	if x != nil {
		return x.MaterialUuid
	}
	return ""
}

type ToggleLikeOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLiked       bool                   `protobuf:"varint,1,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`          // Состояние лайка
	LikesCount    int32                  `protobuf:"varint,2,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"` // Количество лайков
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeOut) Reset() {
	*x = ToggleLikeOut{}
	mi := &file_api_materials_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeOut) ProtoMessage() {}

func (x *ToggleLikeOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeOut.ProtoReflect.Descriptor instead.
func (*ToggleLikeOut) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{13}
}

func (x *ToggleLikeOut) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *ToggleLikeOut) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

type MaterialDeletedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	OwnerUuid     string                 `protobuf:"bytes,2,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterialDeletedMessage) Reset() {
	*x = MaterialDeletedMessage{}
	mi := &file_api_materials_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialDeletedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialDeletedMessage) ProtoMessage() {}

func (x *MaterialDeletedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialDeletedMessage.ProtoReflect.Descriptor instead.
func (*MaterialDeletedMessage) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{14}
}

func (x *MaterialDeletedMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MaterialDeletedMessage) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *MaterialDeletedMessage) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CreatedMaterial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedMaterial) Reset() {
	*x = CreatedMaterial{}
	mi := &file_api_materials_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedMaterial) ProtoMessage() {}

func (x *CreatedMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedMaterial.ProtoReflect.Descriptor instead.
func (*CreatedMaterial) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{15}
}

func (x *CreatedMaterial) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

type EditMaterialMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	OwnerUuid     string                 `protobuf:"bytes,2,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	EditedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMaterialMessage) Reset() {
	*x = EditMaterialMessage{}
	mi := &file_api_materials_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMaterialMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMaterialMessage) ProtoMessage() {}

func (x *EditMaterialMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMaterialMessage.ProtoReflect.Descriptor instead.
func (*EditMaterialMessage) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{16}
}

func (x *EditMaterialMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *EditMaterialMessage) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *EditMaterialMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditMaterialMessage) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

type ToggleLikeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialUuid  string                 `protobuf:"bytes,1,opt,name=material_uuid,json=materialUuid,proto3" json:"material_uuid,omitempty"`
	IsLiked       bool                   `protobuf:"varint,2,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	LikesCount    int32                  `protobuf:"varint,3,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeMessage) Reset() {
	*x = ToggleLikeMessage{}
	mi := &file_api_materials_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeMessage) ProtoMessage() {}

func (x *ToggleLikeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_materials_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeMessage.ProtoReflect.Descriptor instead.
func (*ToggleLikeMessage) Descriptor() ([]byte, []int) {
	return file_api_materials_proto_rawDescGZIP(), []int{17}
}

func (x *ToggleLikeMessage) GetMaterialUuid() string {
	if x != nil {
		return x.MaterialUuid
	}
	return ""
}

func (x *ToggleLikeMessage) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *ToggleLikeMessage) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

var File_api_materials_proto protoreflect.FileDescriptor

const file_api_materials_proto_rawDesc = "" +
	"\n" +
	"\x13api/materials.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xbb\x01\n" +
	"\x13SaveDraftMaterialIn\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12&\n" +
	"\x0fcover_image_url\x18\x02 \x01(\tR\rcoverImageUrl\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12*\n" +
	"\x11read_time_minutes\x18\x05 \x01(\x05R\x0freadTimeMinutes\"*\n" +
	"\x14SaveDraftMaterialOut\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"#\n" +
	"\rGetMaterialIn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"7\n" +
	"\x0eGetMaterialOut\x12%\n" +
	"\bmaterial\x18\x01 \x01(\v2\t.MaterialR\bmaterial\"\xc7\x04\n" +
	"\bMaterial\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x02 \x01(\tR\townerUuid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12&\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tR\rcoverImageUrl\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12*\n" +
	"\x11read_time_minutes\x18\a \x01(\x05R\x0freadTimeMinutes\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tedited_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\beditedAt\x12=\n" +
	"\fpublished_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12;\n" +
	"\varchived_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"archivedAt\x129\n" +
	"\n" +
	"deleted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x1f\n" +
	"\vlikes_count\x18\x0e \x01(\x05R\n" +
	"likesCount\"D\n" +
	"\x12GetAllMaterialsOut\x12.\n" +
	"\rmaterial_list\x18\x01 \x03(\v2\t.MaterialR\fmaterialList\"\xca\x01\n" +
	"\x0eEditMaterialIn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12&\n" +
	"\x0fcover_image_url\x18\x03 \x01(\tR\rcoverImageUrl\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12*\n" +
	"\x11read_time_minutes\x18\x06 \x01(\x05R\x0freadTimeMinutes\"8\n" +
	"\x0fEditMaterialOut\x12%\n" +
	"\bmaterial\x18\x01 \x01(\v2\t.MaterialR\bmaterial\"&\n" +
	"\x10DeleteMaterialIn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"'\n" +
	"\x11PublishMaterialIn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\";\n" +
	"\x12PublishMaterialOut\x12%\n" +
	"\bmaterial\x18\x01 \x01(\v2\t.MaterialR\bmaterial\"(\n" +
	"\x12ArchivedMaterialIn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"3\n" +
	"\fToggleLikeIn\x12#\n" +
	"\rmaterial_uuid\x18\x01 \x01(\tR\fmaterialUuid\"K\n" +
	"\rToggleLikeOut\x12\x19\n" +
	"\bis_liked\x18\x01 \x01(\bR\aisLiked\x12\x1f\n" +
	"\vlikes_count\x18\x02 \x01(\x05R\n" +
	"likesCount\"\x86\x01\n" +
	"\x16MaterialDeletedMessage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x02 \x01(\tR\townerUuid\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"8\n" +
	"\x0fCreatedMaterial\x12%\n" +
	"\bmaterial\x18\x01 \x01(\v2\t.MaterialR\bmaterial\"\x97\x01\n" +
	"\x13EditMaterialMessage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1d\n" +
	"\n" +
	"owner_uuid\x18\x02 \x01(\tR\townerUuid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x127\n" +
	"\tedited_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\beditedAt\"t\n" +
	"\x11ToggleLikeMessage\x12#\n" +
	"\rmaterial_uuid\x18\x01 \x01(\tR\fmaterialUuid\x12\x19\n" +
	"\bis_liked\x18\x02 \x01(\bR\aisLiked\x12\x1f\n" +
	"\vlikes_count\x18\x03 \x01(\x05R\n" +
	"likesCount2\xee\x03\n" +
	"\x10MaterialsService\x12B\n" +
	"\x11SaveDraftMaterial\x12\x14.SaveDraftMaterialIn\x1a\x15.SaveDraftMaterialOut\"\x00\x120\n" +
	"\vGetMaterial\x12\x0e.GetMaterialIn\x1a\x0f.GetMaterialOut\"\x00\x12@\n" +
	"\x0fGetAllMaterials\x12\x16.google.protobuf.Empty\x1a\x13.GetAllMaterialsOut\"\x00\x123\n" +
	"\fEditMaterial\x12\x0f.EditMaterialIn\x1a\x10.EditMaterialOut\"\x00\x12<\n" +
	"\x0fPublishMaterial\x12\x12.PublishMaterialIn\x1a\x13.PublishMaterialOut\"\x00\x12=\n" +
	"\x0eDeleteMaterial\x12\x11.DeleteMaterialIn\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\x10ArchivedMaterial\x12\x13.ArchivedMaterialIn\x1a\x16.google.protobuf.Empty\"\x00\x12-\n" +
	"\n" +
	"ToggleLike\x12\r.ToggleLikeIn\x1a\x0e.ToggleLikeOut\"\x00B\x0fZ\rpkg/materialsb\x06proto3"

var (
	file_api_materials_proto_rawDescOnce sync.Once
	file_api_materials_proto_rawDescData []byte
)

func file_api_materials_proto_rawDescGZIP() []byte {
	file_api_materials_proto_rawDescOnce.Do(func() {
		file_api_materials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_materials_proto_rawDesc), len(file_api_materials_proto_rawDesc)))
	})
	return file_api_materials_proto_rawDescData
}

var file_api_materials_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_materials_proto_goTypes = []any{
	(*SaveDraftMaterialIn)(nil),    // 0: SaveDraftMaterialIn
	(*SaveDraftMaterialOut)(nil),   // 1: SaveDraftMaterialOut
	(*GetMaterialIn)(nil),          // 2: GetMaterialIn
	(*GetMaterialOut)(nil),         // 3: GetMaterialOut
	(*Material)(nil),               // 4: Material
	(*GetAllMaterialsOut)(nil),     // 5: GetAllMaterialsOut
	(*EditMaterialIn)(nil),         // 6: EditMaterialIn
	(*EditMaterialOut)(nil),        // 7: EditMaterialOut
	(*DeleteMaterialIn)(nil),       // 8: DeleteMaterialIn
	(*PublishMaterialIn)(nil),      // 9: PublishMaterialIn
	(*PublishMaterialOut)(nil),     // 10: PublishMaterialOut
	(*ArchivedMaterialIn)(nil),     // 11: ArchivedMaterialIn
	(*ToggleLikeIn)(nil),           // 12: ToggleLikeIn
	(*ToggleLikeOut)(nil),          // 13: ToggleLikeOut
	(*MaterialDeletedMessage)(nil), // 14: MaterialDeletedMessage
	(*CreatedMaterial)(nil),        // 15: CreatedMaterial
	(*EditMaterialMessage)(nil),    // 16: EditMaterialMessage
	(*ToggleLikeMessage)(nil),      // 17: ToggleLikeMessage
	(*timestamppb.Timestamp)(nil),  // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 19: google.protobuf.Empty
}
var file_api_materials_proto_depIdxs = []int32{
	4,  // 0: GetMaterialOut.material:type_name -> Material
	18, // 1: Material.created_at:type_name -> google.protobuf.Timestamp
	18, // 2: Material.edited_at:type_name -> google.protobuf.Timestamp
	18, // 3: Material.published_at:type_name -> google.protobuf.Timestamp
	18, // 4: Material.archived_at:type_name -> google.protobuf.Timestamp
	18, // 5: Material.deleted_at:type_name -> google.protobuf.Timestamp
	4,  // 6: GetAllMaterialsOut.material_list:type_name -> Material
	4,  // 7: EditMaterialOut.material:type_name -> Material
	4,  // 8: PublishMaterialOut.material:type_name -> Material
	18, // 9: MaterialDeletedMessage.deleted_at:type_name -> google.protobuf.Timestamp
	4,  // 10: CreatedMaterial.material:type_name -> Material
	18, // 11: EditMaterialMessage.edited_at:type_name -> google.protobuf.Timestamp
	0,  // 12: MaterialsService.SaveDraftMaterial:input_type -> SaveDraftMaterialIn
	2,  // 13: MaterialsService.GetMaterial:input_type -> GetMaterialIn
	19, // 14: MaterialsService.GetAllMaterials:input_type -> google.protobuf.Empty
	6,  // 15: MaterialsService.EditMaterial:input_type -> EditMaterialIn
	9,  // 16: MaterialsService.PublishMaterial:input_type -> PublishMaterialIn
	8,  // 17: MaterialsService.DeleteMaterial:input_type -> DeleteMaterialIn
	11, // 18: MaterialsService.ArchivedMaterial:input_type -> ArchivedMaterialIn
	12, // 19: MaterialsService.ToggleLike:input_type -> ToggleLikeIn
	1,  // 20: MaterialsService.SaveDraftMaterial:output_type -> SaveDraftMaterialOut
	3,  // 21: MaterialsService.GetMaterial:output_type -> GetMaterialOut
	5,  // 22: MaterialsService.GetAllMaterials:output_type -> GetAllMaterialsOut
	7,  // 23: MaterialsService.EditMaterial:output_type -> EditMaterialOut
	10, // 24: MaterialsService.PublishMaterial:output_type -> PublishMaterialOut
	19, // 25: MaterialsService.DeleteMaterial:output_type -> google.protobuf.Empty
	19, // 26: MaterialsService.ArchivedMaterial:output_type -> google.protobuf.Empty
	13, // 27: MaterialsService.ToggleLike:output_type -> ToggleLikeOut
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_materials_proto_init() }
func file_api_materials_proto_init() {
	if File_api_materials_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_materials_proto_rawDesc), len(file_api_materials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_materials_proto_goTypes,
		DependencyIndexes: file_api_materials_proto_depIdxs,
		MessageInfos:      file_api_materials_proto_msgTypes,
	}.Build()
	File_api_materials_proto = out.File
	file_api_materials_proto_goTypes = nil
	file_api_materials_proto_depIdxs = nil
}
